create table session
(
    id         bigint generated by default as identity,
    sid        varchar(255),
    user_id    varchar(255),
    user_name  varchar(255),
    user_email varchar(255),
    primary key (id)
);